### ISSUE TITLE
Outage 2023/03/08

### ISSUE THREAD

**Issue by SteveHenley** [rchain-community/mainnet-outage#2] opened 2023-03-29 12:52 UTC
Problem: DNS was inoperable for all of rhovision.org and rchain.coop domains causing complete outage.

Root Cause: There were three root causes for this outage.

There was an old Vercel website serving DNS r-pub.com names for the former RPC marketplace website.
The pfsense and Hetzner firewalls were locked down as part of the mainnet roll-out and the (unknown) trampoline used by Vercel was mistaken as an attack. Our defense to the attack made the resulting DNS conflict cause catastrophic failure in all ns1.r-pub.com server DNS names
The secondary DNS (afraid.org) uses IPv6 for synchronizing DNS names, and IPv6 was shut down on the Hetzner firewalls
Resolution: Eliminate the Vercel project for the former RPC marketplace website, and open IPv6 DNS ports on Hetzner. Wait for two hours for DNS TTL to expire, and update the DNS zone files to resync with secondary DNS

DNS zone updates in 4eabc27

Original issue opened 3 weeks ago.

**Comment by Bill-Kunj** [comment] 2023-04-02 10:43
Original outage caused by a confounding Vercel factor which is no longer relevant. There are no other services using our DNS names.
Closing

**Closed by Bill-Kunj** 2023-04-02 10:43 UTC
Labels: Outage
