### ISSUE TITLE
Server 200 is down and no Raft logging by leader and followers

### ISSUE THREAD

**Issue by David405** [rchain-community/mainnet-outage#58] opened 2023-09-03 17:11 UTC
Alert: Server 200 is down.

Dashboard diagnostics: http://167.235.8.82:3000/d/be754396-d2ea-4e15-9a92-9b92b8dfcf61/l1-monitoring1?orgId=1

note when selecting server 200 it has stopped. And the fault tolerance has gone to 0.

Server 200 shows Raft logging has stopped on this dashboard: http://167.235.8.82:3000/d/bebbdd9c-7013-4a54-9f56-5272a66df262/l1-raft-monitoring?orgId=1

**Comment by Bill-Kunj** [comment] 2023-09-03 17:38
Duplicate of #57

**Closed as completed by Bill-Kunj** 2023-09-03 17:38 UTC
Labels: fire-drill
